#logging.level.org.hibernate.SQL: debug
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info